import { Menu } from "@/components/Menu/Menu";
import Lang from "@/components/Nav/Lang";
import { i18n } from "@/config/i18n.config";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  const languages = i18n.locales.map((lang) => ({ lang }));
  return languages;
}

export const metadata: Metadata = {
  title: "YouTube Piloto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang}>
      <body className={`flex flex-col h-screen ${inter.className}`}>
        <nav className="bg-primary bg-opacity-60 p-4 flex items-center justify-between">
          <Menu />
          <Lang />
        </nav>
        <main className="h-full w-full bg-secondary text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
